name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd spring-boot-server &&
            git pull origin master &&
            sudo docker compose -f compose.prod.yaml up --build
          '

      - name: Wait for deployment
        run: sleep 60

      - name: Check deployment
        env:
          HOST: ${{ secrets.EC2_HOST }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://${HOST}:${API_ENDPOINT}/api/health)
          if [ $response = "200" ]; then
            echo "Deployment successful!"
          else
            echo "Deployment failed!"
            exit 1
          fi